# Generated by Django 3.2.25 on 2025-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Weight in grams', max_digits=6),
            preserve_default=False,
        ),
    ]
